addSbtPlugin("com.eed3si9n"             % "sbt-buildinfo"       % "0.13.1")
addSbtPlugin("org.foundweekends.giter8" % "sbt-giter8-scaffold" % "0.17.0")
addSbtPlugin("com.codecommit"           % "sbt-github-packages" % "0.5.3")
addSbtPlugin("com.github.sbt"           % "sbt-git"             % "2.1.0")
addSbtPlugin("com.github.sbt"           % "sbt-dynver"          % "5.1.1")
addSbtPlugin("org.scalameta"            % "sbt-scalafmt"        % "2.5.5")
